server:
  port: 9092
spring:
  jpa: 
    # hibernate.ddl-auto: none
    show-sql: false
    properties:
        hibernate:
            jdbc.batch_size: 1000
            order_inserts: true
    hibernate:
        ddl-auto: create        
  # h2:
  #   console:
  #     enabled: true
  # datasource:
    # url: jdbc:h2:~/test
    # username: sa
    # password:
    # driver-class-name: org.h2.Driver
    # platform: h2
    # initialization-mode: always